### ISSUE TITLE
Weird location-put behaviour if ID isn't specified

### ISSUE THREAD

**Issue by io7m** [io7m-com/cardant#27]
```
[cardant]$ location-put --id 0b3a0e83-3e94-411f-b01e-ed042614ca84 --name House
┌───────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Attribute     │ Value                                                                                                                                                        │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Location ID   │ 0b3a0e83-3e94-411f-b01e-ed042614ca84                                                                                                                         │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ House                                                                                                                                                        │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Parent        │ None                                                                                                                                                         │
└───────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[cardant]$ location-put --parent 0b3a0e83-3e94-411f-b01e-ed042614ca84 --name Windows01
com.io7m.cardant.model.CAValidityException: A location's parent cannot equal itself
	at com.io7m.cardant.model@1.0.0-SNAPSHOT/com.io7m.cardant.model.CALocation.lambda$new$0(CALocation.java:65)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.io7m.cardant.model@1.0.0-SNAPSHOT/com.io7m.cardant.model.CALocation.<init>(CALocation.java:63)
	at com.io7m.cardant.shell@1.0.0-SNAPSHOT/com.io7m.cardant.shell.internal.CAShellCmdLocationPut.modifyExistingLocation(CAShellCmdLocationPut.java:192)
	at com.io7m.cardant.shell@1.0.0-SNAPSHOT/com.io7m.cardant.shell.internal.CAShellCmdLocationPut.onExecute(CAShellCmdLocationPut.java:158)
	at com.io7m.cardant.shell@1.0.0-SNAPSHOT/com.io7m.cardant.shell.internal.CAShell.runForOneLine(CAShell.java:250)
	at com.io7m.cardant.shell@1.0.0-SNAPSHOT/com.io7m.cardant.shell.internal.CAShell.run(CAShell.java:146)
	at com.io7m.cardant.main@1.0.0-SNAPSHOT/com.io7m.cardant.main.internal.CMCmdShell.onExecute(CMCmdShell.java:120)
	at com.io7m.quarrel.core@1.5.0/com.io7m.quarrel.core.internal.QCommandContext.execute(QCommandContext.java:207)
	at com.io7m.quarrel.core@1.5.0/com.io7m.quarrel.core.QApplicationType.run(QApplicationType.java:94)
	at com.io7m.cardant.main@1.0.0-SNAPSHOT/com.io7m.cardant.main.CAMain.run(CAMain.java:153)
	at com.io7m.cardant.main@1.0.0-SNAPSHOT/com.io7m.cardant.main.CAMain.mainExitless(CAMain.java:128)
	at com.io7m.cardant.main@1.0.0-SNAPSHOT/com.io7m.cardant.main.CAMain.main(CAMain.java:113)
```

**Comment by io7m** [comment]
I now can't reproduce this.

**Comment by io7m** [comment]
It happened again yesterday. Still a real problem.
